

spring:
  application:
    name: cards
  
  datasource:
    url: jdbc:h2:mem:cardsdb
    username: admin
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
  
  h2:
    console:
      enabled: true

 
server:
  port: 9004
  

management:
  endpoints:
    web:
      exposure:
        include: '*'
#Microservices talks to zipkin URL via this URL, this is the end-point given in their documentation.
  zipkin:
    tracing:
      endpoint: "http://localhost:9411/api/v2/spans"
      

      
      
  info:
    env:
      enabled: true
      
  #each and Every operation will be tracked and send to zipkin
  tracing:
    sampling:
      probability: 1.0

info:
  app:
    name: cards
    description: cards microservice
    version: 1.0.0
  location: Hyderabad
  
 
 
#Eureka-client config
 
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    
    #overriding defaultZone(magic port : 8761) for eureka-server
    service-url:
      defaultZone: http://localhost:9002/eureka/
  instance:
    prefer-ip-address: true
    
    
#enabling tracing pattern for distributed transactions   
logging:
  pattern:
    level: '%5p [%X {traceId:-}, %X {spanId:-}, ${spring.application.name:}, ]'
    
    # generate logs to a file in specific folder
  file:
    name: cards_logs/cards.log

