

spring:
  application:
    name: cards
  
  datasource:
    url: jdbc:h2:mem:cardsdb
    username: admin
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
  
  h2:
    console:
      enabled: true

 
server:
  port: 9004
  

management:
  endpoints:
    web:
      exposure:
        include: '*'
 
  info:
    env:
      enabled: true


info:
  app:
    name: cards
    description: cards microservice
    version: 1.0.0
  location: Hyderabad
  
 
 
#Eureka-client config
 
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    
    #overriding defaultZone(magic port : 8761) for eureka-server
    service-url:
      defaultZone: http://localhost:9002/eureka/
  instance:
    prefer-ip-address: true

