
spring:
  application:
    name: loans
  #DB config
  datasource:
    url: jdbc:h2:mem:loansdb
    username: admin
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
  #enable h2-console
  h2:
    console:
      enabled: true

#change the port  - u can run in another port number(while running change the port - eurekaServer)
server:
  port: 9005
  
#enable actuator endpoints 
management:
  endpoints:
    web:
      exposure:
        include: '*'
  #enable info endpoint to see project info
  info:
    env:
      enabled: true

#project information
info:
  app:
    name: loans
    description: loans microservice
    version: 1.0.0
  location: Hyderabad
  
  
# to allow h2 work on cloud


#eruka-server config

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    
    #overriding defaultZone(magic port : 8761) for eureka-server
    service-url:
      defaultZone: http://localhost:9002/eureka/
  instance:
    prefer-ip-address: true



#enabling tracing pattern for distributed transactions   
logging:
  pattern:
    level: '%5p [%X {traceId:-}, %X {spanId:-}, ${spring.application.name:}, ]'
    
    # generate logs to a file in specific folder
  file:
    name: loans_logs/loans.log
