
spring:
  application:
    name: accounts
  #DB config
  datasource:
    url: jdbc:h2:mem:accountsdb
    username: admin
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
  #enable h2-console
  h2:
    console:
      enabled: true
  #to enable circuit-breaker
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true



#change the port  
server:
  port: 9003
  
#enable actuator endpoints 
management:
  endpoints:
    web:
      exposure:
        include: '*'
  #enable info endpoint to see project info
  info:
    env:
      enabled: true
      
 #each and Every operation will be tracked and send to zipkin
  tracing:
    sampling:
      probability: 1.0
      
  #Microservices talks to zipkin URL via this URL, this is the end-point given in their documentation.
  zipkin:
    tracing:
      endpoint: "http://localhost:9411/api/v2/spans"

#project information
info:
  app:
    name: accounts
    description: accounts microservice
    version: 1.0.0
  location: Hyderabad
  
  
# to allow h2 work on cloud




#Eureka-client configuration
       
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    
    #overriding defaultZone(magic port : 8761) for eureka-server
    service-url:
      defaultZone: http://localhost:9002/eureka/
  instance:
    prefer-ip-address: true


#enabling tracing pattern for distributed transactions   
logging:
  pattern:
    level: '%5p [%X {traceId:-}, %X {spanId:-}, ${spring.application.name:}, ]'
    
    # generate logs to a file in specific folder
  file:
    name: accounts_logs/accounts.log
  logback:
    rollingpolicy:
      file-name-pattern: accounts_logs/accounts.%d{yyyy-MM-dd}.%i.log
    max-file-size: 1MB
      
#logging:
#  level:
#    root: INFO
#  file:
#    name: /path/to/your/logfile.log
#  logback:
#    rollingpolicy:
#      file-name-pattern: /path/to/your/logfile.%d{yyyy-MM-dd}.%i.log
#    max-file-size: 10MB
#    max-history: 30


#resilience4J default configs
resilience4j:
  circuitbreaker:
    configs: 
      default:
        sliding-window-size: 5
        permitted-number-of-calls-in-half-open-state: 2
        failure-rate-threshold: 50
        wait-duration-in-open-state: 30s
      